In [1]:
import duckdb
import os
from pathlib import Path

# ensuring that os.chdir is idempotent and that we are in the project root directory,
# not inside the notebooks directory
if 'notebooks' not in os.listdir(Path.cwd()):
    print("Still inside notebooks directory, changing to project root directory.")
    os.chdir(Path.cwd().parent)
    print("Current working directory after change: ", Path.cwd())
else:
    print(f"Already in parent directory (current working directory: {Path.cwd()})")


# load config
from src.io.load_config import load_config
sw_config = load_config()['space_weather']

# load T1 and T2 dataset dir
T1_dir = sw_config['preprocessing']['k_index']['T1_output_dir']
T2_dir = sw_config['transform']['k_index']['T2_output_dir']

Still inside notebooks directory, changing to project root directory.
Current working directory after change:  d:\data-sci-projects\space-weather-project-scrub

# Test endpoints from CDAWeb HAPI

CDAWeb HAPI description can be found at https://cdaweb.gsfc.nasa.gov/hapi

In [2]:
import pandas as pd
import requests
from io import StringIO

## `/info`

In [3]:
def fetch_info_omni_hro2_1min(dataset_id="OMNI_HRO2_1MIN",
                            base_url="https://cdaweb.gsfc.nasa.gov/hapi",
                            ):

    # as per HAPI description, endpoints respond to HTTP GET requests 
    response = requests.get(base_url + '/info',
                            params={"id": dataset_id},
                            timeout=120)
    
    response.raise_for_status()

    return response.json()

In [4]:
info_endpoint_test = fetch_info_omni_hro2_1min()

In [9]:
info_endpoint_test

{'HAPI': '2.0',
 'resourceURL': 'https://cdaweb.gsfc.nasa.gov/misc/NotesO.html#OMNI_HRO2_1MIN',
 'contact': 'J.H. King, N. Papatashvilli @ AdnetSystems, NASA GSFC',
 'parameters': [{'name': 'Time',
   'length': 24,
   'units': 'UTC',
   'type': 'isotime',
   'fill': None},
  {'name': 'IMF',
   'description': 'OMNI ID code for the source spacecraft for time-shifted IMF values (see OMNI documentation link for codes)',
   'units': None,
   'type': 'integer',
   'fill': '99'},
  {'name': 'PLS',
   'description': 'OMNI ID code for the source spacecraft  for time-shifted IP plasma values (see OMNI documentation link for codes)',
   'units': None,
   'type': 'integer',
   'fill': '99'},
  {'name': 'IMF_PTS',
   'description': 'Number of fine time scale points in IMF averages',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'PLS_PTS',
   'description': 'Number of fine time scale points in plasma averages',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'percent_interp',
   'description': 'Percent interpolated',
   'units': None,
   'type': 'integer',
   'fill': '999'},
  {'name': 'Timeshift',
   'description': 'Timeshift (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'RMS_Timeshift',
   'description': 'RMS Timeshift (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'RMS_phase',
   'description': 'RMS, Phase front normal (nT) ',
   'units': 'nT',
   'type': 'double',
   'fill': '99.99'},
  {'name': 'Time_btwn_obs',
   'description': 'Time between observations (seconds)',
   'units': 'seconds',
   'type': 'integer',
   'fill': '999999'},
  {'name': 'F',
   'description': 'Magnitude of avg. field vector (nT) (last currently-available OMNI B-field data Apr 12, 2026)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BX_GSE',
   'description': 'Bx (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BY_GSE',
   'description': 'By (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BZ_GSE',
   'description': 'Bz (nT), GSE',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BY_GSM',
   'description': 'By (nT), GSM, determined from post-shift GSE components',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BZ_GSM',
   'description': 'Bz (nT), GSM, determined from post-shift GSE components',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'RMS_SD_B',
   'description': 'RMS SD B scalar (nT)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'RMS_SD_fld_vec',
   'description': 'RMS SD field vector (nT)',
   'units': 'nT',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'flow_speed',
   'description': 'Flow Speed (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vx',
   'description': 'Vx Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vy',
   'description': 'Vy Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'Vz',
   'description': 'Vz Velocity (km/s), GSE',
   'units': 'km/s',
   'type': 'double',
   'fill': '99999.9'},
  {'name': 'proton_density',
   'description': 'Proton density (n/cc) (last currently-available OMNI plasma data Apr 12, 2026)',
   'units': 'n/cc',
   'type': 'double',
   'fill': '999.99'},
  {'name': 'T',
   'description': 'Temperature (K)',
   'units': 'K',
   'type': 'double',
   'fill': '9999999.0'},
  {'name': 'NaNp_Ratio',
   'description': 'Alpha/Proton Density Ratio',
   'units': ' ',
   'type': 'double',
   'fill': '9.999'},
  {'name': 'Pressure',
   'description': 'Flow pressure (nPa)',
   'units': 'nPa',
   'type': 'double',
   'fill': '99.99'},
  {'name': 'E',
   'description': 'Electric Field (mV/m)',
   'units': 'mV/m',
   'type': 'double',
   'fill': '999.99'},
  {'name': 'Beta',
   'description': 'Plasma beta',
   'units': None,
   'type': 'double',
   'fill': '999.99'},
  {'name': 'Mach_num',
   'description': 'Alfven mach number',
   'units': None,
   'type': 'double',
   'fill': '999.9'},
  {'name': 'Mgs_mach_num',
   'description': '1AU IP Magnetosonic mach number',
   'units': None,
   'type': 'double',
   'fill': '99.9'},
  {'name': 'x',
   'description': 'X s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'y',
   'description': 'Y s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'z',
   'description': 'Z s/c (Re), GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_x',
   'description': 'Bow Shock Nose (Re) location, X, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_y',
   'description': 'Bow Shock Nose (Re) location, Y, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'BSN_z',
   'description': 'Bow Shock Nose (Re) location, Z, GSE',
   'units': 'Re',
   'type': 'double',
   'fill': '9999.99'},
  {'name': 'AE_INDEX',
   'description': 'AE - 1-minute AE-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'AL_INDEX',
   'description': 'AL - 1-minute AL-index, from WDC Kyoto (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'AU_INDEX',
   'description': 'AU - 1-minute AU-index,from WDC Kyoto  (Final 1988/001-1988/182, Provisional 1990/001-2020/365)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'SYM_D',
   'description': 'SYM/D - 1-minute SYM/D index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'SYM_H',
   'description': 'SYM/H - 1-minute SYM/H index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'ASY_D',
   'description': 'ASY/D - 1-minute ASY/D index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'},
  {'name': 'ASY_H',
   'description': 'ASY/H - 1-minute ASY/H index,from WDC Kyoto (1981/001-2026/090)',
   'units': 'nT',
   'type': 'integer',
   'fill': '99999'}],
 'startDate': '1995-01-01T00:00:00Z',
 'stopDate': '2026-04-13T01:15:00Z',
 'status': {'code': 1200, 'message': 'OK'}}

In [10]:
pd.DataFrame(info_endpoint_test['parameters'])

,name,length,units,type,fill,description
0,Time,24.0,UTC,isotime,None,NaN
1,IMF,NaN,None,integer,99,OMNI ID code for the source spacecraft for tim...
2,PLS,NaN,None,integer,99,OMNI ID code for the source spacecraft for ti...
3,IMF_PTS,NaN,None,integer,999,Number of fine time scale points in IMF averages
4,PLS_PTS,NaN,None,integer,999,Number of fine time scale points in plasma ave...
5,percent_interp,NaN,None,integer,999,Percent interpolated
6,Timeshift,NaN,seconds,integer,999999,Timeshift (seconds)
7,RMS_Timeshift,NaN,seconds,integer,999999,RMS Timeshift (seconds)
8,RMS_phase,NaN,nT,double,99.99,"RMS, Phase front normal (nT)"
9,Time_btwn_obs,NaN,seconds,integer,999999,Time between observations (seconds)
10,F,NaN,nT,double,9999.99,Magnitude of avg. field vector (nT) (last curr...
11,BX_GSE,NaN,nT,double,9999.99,"Bx (nT), GSE"
12,BY_GSE,NaN,nT,double,9999.99,"By (nT), GSE"
13,BZ_GSE,NaN,nT,double,9999.99,"Bz (nT), GSE"
14,BY_GSM,NaN,nT,double,9999.99,"By (nT), GSM, determined from post-shift GSE c..."
15,BZ_GSM,NaN,nT,double,9999.99,"Bz (nT), GSM, determined from post-shift GSE c..."
16,RMS_SD_B,NaN,nT,double,9999.99,RMS SD B scalar (nT)
17,RMS_SD_fld_vec,NaN,nT,double,9999.99,RMS SD field vector (nT)
18,flow_speed,NaN,km/s,double,99999.9,"Flow Speed (km/s), GSE"
19,Vx,NaN,km/s,double,99999.9,"Vx Velocity (km/s), GSE"
20,Vy,NaN,km/s,double,99999.9,"Vy Velocity (km/s), GSE"
21,Vz,NaN,km/s,double,99999.9,"Vz Velocity (km/s), GSE"
22,proton_density,NaN,n/cc,double,999.99,Proton density (n/cc) (last currently-availabl...
23,T,NaN,K,double,9999999.0,Temperature (K)
24,NaNp_Ratio,NaN,,double,9.999,Alpha/Proton Density Ratio
25,Pressure,NaN,nPa,double,99.99,Flow pressure (nPa)
26,E,NaN,mV/m,double,999.99,Electric Field (mV/m)
27,Beta,NaN,None,double,999.99,Plasma beta
28,Mach_num,NaN,None,double,999.9,Alfven mach number
29,Mgs_mach_num,NaN,None,double,99.9,1AU IP Magnetosonic mach number
30,x,NaN,Re,double,9999.99,"X s/c (Re), GSE"
31,y,NaN,Re,double,9999.99,"Y s/c (Re), GSE"
32,z,NaN,Re,double,9999.99,"Z s/c (Re), GSE"
33,BSN_x,NaN,Re,double,9999.99,"Bow Shock Nose (Re) location, X, GSE"
34,BSN_y,NaN,Re,double,9999.99,"Bow Shock Nose (Re) location, Y, GSE"
35,BSN_z,NaN,Re,double,9999.99,"Bow Shock Nose (Re) location, Z, GSE"
36,AE_INDEX,NaN,nT,integer,99999,"AE - 1-minute AE-index, from WDC Kyoto (Final ..."
37,AL_INDEX,NaN,nT,integer,99999,"AL - 1-minute AL-index, from WDC Kyoto (Final ..."
38,AU_INDEX,NaN,nT,integer,99999,"AU - 1-minute AU-index,from WDC Kyoto (Final ..."
39,SYM_D,NaN,nT,integer,99999,"SYM/D - 1-minute SYM/D index,from WDC Kyoto (1..."
40,SYM_H,NaN,nT,integer,99999,"SYM/H - 1-minute SYM/H index,from WDC Kyoto (1..."
41,ASY_D,NaN,nT,integer,99999,"ASY/D - 1-minute ASY/D index,from WDC Kyoto (1..."
42,ASY_H,NaN,nT,integer,99999,"ASY/H - 1-minute ASY/H index,from WDC Kyoto (1..."

In [ ]:
query_var = 'BX_GSE'
display(
    pd.DataFrame(info_endpoint_test['parameters']).query(f"name=='{query_var}'")
)

display(
    pd.DataFrame(info_endpoint_test['parameters']).query(f"name=='{query_var}'").fill.item()
)

## `/data` (with params)

In [6]:
# https://cdaweb.gsfc.nasa.gov/hapi/data?id=OMNI_HRO2_1MIN&parameters=F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure&time.min=2021-11-21T00:00:00Z&time.max=2021-11-22T00:00:00Z&format=csv
def fetch_data_omni_hro2_1min(start_utc: str,
                         end_utc: str,
                         vars: str="F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure"
                         ):

    url = "https://cdaweb.gsfc.nasa.gov/hapi/data"

    params = {
        "id": "OMNI_HRO2_1MIN",
        "time.min": start_utc,
        "time.max": end_utc
    }
    
    if vars:
        # no intermediate or trailing whitespaces allowed
        vars = vars.replace(" ", "")
        params['parameters'] = vars

    print("Requesting solar dataset from OMNI_HRO2_1MIN...")
    response = requests.get(url, params=params, timeout=120)
    response.raise_for_status()
    print("Request succeeded.")

    df = pd.read_csv(StringIO(response.text),
                     comment="#",
                     header=None)
    df.columns = ["time"] + vars.split(',')
    return df

In [ ]:
from datetime import datetime, timezone, timedelta

In [8]:
omni = fetch_data_omni_hro2_1min(
    start_utc="2021-11-21T00:00:00Z",
    end_utc="2021-11-22T00:00:00Z"
)
omni

Requesting solar dataset from OMNI_HRO2_1MIN...
Request succeeded.

,time,F,BX_GSE,BY_GSM,BZ_GSM,flow_speed,proton_density,Pressure
0,2021-11-21T00:00:00.000Z,4.79,1.87,-2.40,-3.37,99999.9,999.99,99.99
1,2021-11-21T00:01:00.000Z,5.73,4.25,0.29,2.60,99999.9,999.99,99.99
2,2021-11-21T00:02:00.000Z,4.90,1.72,-3.04,-3.39,583.6,4.70,3.20
3,2021-11-21T00:03:00.000Z,4.92,2.03,-3.04,-3.23,583.6,4.70,3.20
4,2021-11-21T00:04:00.000Z,5.00,1.68,-2.93,-3.67,583.6,4.70,3.20
...,...,...,...,...,...,...,...,...
1435,2021-11-21T23:55:00.000Z,3.69,2.28,-2.76,0.48,612.4,2.33,1.75
1436,2021-11-21T23:56:00.000Z,3.76,1.76,-3.15,0.31,619.3,2.45,1.88
1437,2021-11-21T23:57:00.000Z,3.75,-0.65,-3.07,-1.14,635.0,2.35,1.90
1438,2021-11-21T23:58:00.000Z,3.95,-1.41,-3.01,-2.11,643.1,2.31,1.91
1439,2021-11-21T23:59:00.000Z,3.93,-1.73,-2.52,-2.38,640.5,2.38,1.95